{
    imports =
        [
            ./archivers
            ./exiftool
            ./eza
            ./ffmpeg
            ./flac
            ./fzf
            ./gallery-dl
            ./git
            ./go
            ./htop
            ./imagemagick
            ./neovim
            ./ripgrep
            ./rsync
            ./shells
            ./sshfs
            ./texlive
            ./tmux
            ./yt
            ./zoxide
        ];
}
